server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  #    file ? ???? ?? ?? native ??
#  profiles:
#    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: file://${user.home}/Desktop/ecommerce-git/git-local-repo
        git:
          uri: https://github.com/khj923265/spring-cloud-config
#          username: [username] private repo ? ?? ?????
#          passphrase: [password]

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh