server:
  port: 8888

spring:
  application:
    name: config-service
#    file ? ???? ?? ?? native ??
#  profiles:
#    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: file://${user.home}/Desktop/ecommerce-git/git-local-repo
        git:
          uri: https://github.com/khj923265/spring-cloud-config
#          username: [username] private repo ? ?? ?????
#          passphrase: [password]